model_selection:
    model:
      LR:
        search_param_grid:
          Cs: 
           - 10
           - 20
           - 30
           - 5
          penalty: 
           - l1
           - l2
          solver:
           - saga     
      SVC:
        search_param_grid:
          C:
           - 0.1
           - 1
           - 10
          kernel:
           - linear
           - poly 
           - rbf
      LSVC:
        search_param_grid:
          penalty:
           - l1
           - l2
          C: 
           - 0.1
           - 1
           - 10
      RFC:
        search_param_grid:
          n_estimators: 
           - 100
           - 200
           - 300
          max_depth: 
           - 5
           - 10
          min_samples_split: 
           - 2
           - 5
           - 10
          min_samples_leaf: 
           - 1
           - 2
           - 4
     
  
          
        