model_selection:
    model:
      GBC:
        search_param_grid:
          loss :
           - log_loss
           - exponential
          learning_rate: 
           - .5
           - .10
           - .20
          n_estimators :
           - 100
           - 200
          min_samples_split:
           - 5
           - 10
           - 20
           - 30
          min_samples_leaf:
           - 5
           - 10
           - 18
          max_depth:
           - 8
           - 15
           - 20
          max_features:
           - sqrt
           - log2
          ccp_alpha:
           - .8
           - .15 

    
        